### ISSUE TITLE
How to use this application

### ISSUE THREAD

**Issue by gro1729** [shanto268/snip2tex#1]
As a mathematican I like the idea of this application. But how to use?

**Comment by shanto268** [comment]
Hi @gro1729 ,

Firstly, I want to remind you that this app would only work on Macs.

Secondly, for the usage - Just follow the installation procedure and run the app. 

It should create a Menu Bar Tool - ![tool](https://github.com/shanto268/snip2tex/raw/master/assets/menu.png) and all you need to do is press `Snip2TeX` and then a new window (see below) would pop up. 

![window](https://github.com/shanto268/snip2tex/raw/master/assets/app.png) 

Click on the `Snip` button or press `Option+S` and then it would act like a screenshot feature (blue region below) similar to what happens when you press `Cmd+Shift+4` 

![img](https://github.com/shanto268/snip2tex/raw/master/assets/action1.png)

 but now whatever feature you cover should be an equation and once you are done **snapping** it will generate the corresponding `LaTeX` code that you can simply copy.

![w2](https://github.com/shanto268/snip2tex/raw/master/assets/menu2.png)

Hoping this helps. Please let me know if you have any more questions.

Best,
Shanto

**Comment by shanto268** [comment]
Actually I just added support for Windows and Linux as well. So you should be good in that case :)

**Comment by gro1729** [comment]
Thanks for your answer. 
I followed your explanation. But sorry, no window pops up. Do you have any ideas.

**Comment by gro1729** [comment]
Sorry, also after the last update of your nice software-idea I do not get it working on my Mac Mini (Ventura 13.3.1 (22E261)).
I use python 3.10. Could this be the problem, that no windows do pop up?

**Comment by shanto268** [comment]
Hi @gro1729 , can you verify that you have changed the `command` variable inside the code to the path of where your `latexocr` is located?  (you can find it using `which latexocr`) and if the Menu Bar icon pops up?

In the latest version this is done in line 22 : `    command = "/Users/shanto/anaconda3/bin/latexocr"`

Is there any error message that pops up once you run the code? If so please post it here. 

If no error message and if you installed  `latexocr` using `pip install latexocr` I would suggest the following 

1. Reinstall `latexocr`
```
pip uninstall latexocr
pip install 'pix2tex[gui]'
```

2. Close the any instance the code in the terminal

`ps aux | grep python | grep snip2tex.py`

It will print out something like this:

`shanto           56335   0.0  0.1 408909280  17952   ??  SN   Sat03PM   0:05.15 /Users/shanto/anaconda3/bin/python /Users/shanto/Programming/snip2tex/snip2tex.py`

Use the number next to your username (`56335` in my case) to kill the process.

`kill -9 56335`

3. Re-run the code.

`python snip2tex.py`

And it should work 🤞🏽
